config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :orders
  #get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  validates :category, :presence => true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :category, optional: true
    validates :name, :presence => true
    validate :nameWordCountMoreThanOne
    validates :price, :presence => true
    validate :isSaleMoreThanPrice
    CURRENCY_TYPES = ["TL", "USD", "EUR"]

  def nameWordCountMoreThanOne
    errors[:widget] << "name should at least be two words" if name.split.size < 2
  end

  def isSaleMoreThanPrice
    unless sale.nil? || sale == 0
      errors[:comment] << "Sale can't be more than price" if price < sale
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:currency, :name, :price, :sale, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>

  <div class="field form-group">
    <%= form.text_field :category, class:"form-control", placeholder:"Category" %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>
<br/>
<%= link_to 'Show', @category, class:"btn btn-primary" %> |
<%= link_to 'Back', categories_path, class:"btn btn-primary" %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category, class:"btn btn-primary"  %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class:"btn btn-success" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>
<br/>
<%= link_to 'Back', categories_path, class:"btn btn-primary" %>

app/views/categories/show.html.erb
<h1>Category Page</h1>

<table class="table table-striped">
  <tbody>
    <tr>
      <br/>
      <td><strong>Category:</strong></td>
      <td><%= @category.category %></td>
    </tr>
</table>

<%= link_to 'Edit', edit_category_path(@category), class:"btn btn-warning" %> |
<%= link_to 'Back', categories_path, class:"btn btn-primary" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'OrderApp', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to 'Orders', orders_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
           <%= link_to 'Create Order', new_order_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
           <%= link_to 'Categories', categories_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
           <%= link_to 'Create Category', new_category_path, class:"nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <br/>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>OrderApp</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
  <br/>
  <%= render 'home/header' %>
  <div class="container">
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>
  <br/>
  <div class="field form-group">
   
    <%= form.select :currency, Order::CURRENCY_TYPES.map { |s| [s] } %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :price, class:"form-control", placeholder:"Price" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :sale, class:"form-control", placeholder:"Sale" %>
  </div>
  <br/>

  <div class="field form-group">
    <%arr = Category.all.map{|c| [c.category, c.id]} %>
    <%= form.select :category_id, arr%>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>
<br/>
<%= link_to 'Show', @order, class:"btn btn-primary" %> |
<%= link_to 'Back', orders_path, class:"btn btn-primary" %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Currency</th>
      <th>Name</th>
      <th>Price</th>
      <th>Sale</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.currency %></td>
        <td><%= order.name %></td>
        <td><%= order.price %></td>
        <td><%= order.sale %></td>
        <td><%= order.category.category %></td>
        <td><%= link_to 'Show', order, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_order_path(order), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path, class:"btn btn-success" %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>
<br/>
<%= link_to 'Back', orders_path, class:"btn btn-primary" %>

app/views/orders/show.html.erb
<h1>Order Page</h1>

<table class="table table-striped">
  <tbody>
    <tr>
      <br/>
      <td><strong>Currency:</strong></td>
      <td><%= @order.currency %></td>
    </tr>
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @order.name %></td>
    </tr>
    <tr>
      <td><strong>Price:</strong></td>
      <td><%= @order.price %></td>
    </tr>
    <tr>
      <td><strong>Sale:</strong></td>
      <td><%= @order.sale %></td>
    </tr>
    <tr>
      <td><strong>Category:</strong></td>
      <td><%= @order.category.category %></td>
    </tr>
  </tbody>
</table>


<%= link_to 'Edit', edit_order_path(@order), class:"btn btn-warning" %> |
<%= link_to 'Back', orders_path, class:"btn btn-primary" %>